import json
import streamlit as st
from config.metrics import METRIC_TYPES, CATEGORIES, evaluate_metric, format_criterion


_CAT_COLOUR = {
    "Validation":  "#6366f1",
    "Tool":        "#f59e0b",
    "Content":     "#06b6d4",
    "Performance": "#10b981",
    "Path":        "#8b5cf6",
    "Judge":       "#f43f5e",
}


def _badge(text: str, colour: str) -> str:
    return (
        f'<span style="background:{colour};color:#fff;'
        f'padding:2px 10px;border-radius:4px;'
        f'font-size:0.72rem;font-weight:700;letter-spacing:0.5px">'
        f'{text}</span>'
    )


def render() -> None:
    st.header("Analytical Dashboard")

    if not st.session_state.get("run_completed"):
        st.info("No evaluation run yet — go to **Execute Evaluation** and run a scenario.")
        return

    # ── Run history selector (fix #26) ────────────────────────────────────────
    history: list = st.session_state.get("run_history", [])
    tel: dict     = st.session_state.get("telemetry", {})

    if len(history) > 1:
        labels = []
        for i, h in enumerate(reversed(history)):
            ts  = h.get("run_timestamp", "")
            sc  = h.get("run_scenario", "")[:30]
            lbl = f"Run {len(history)-i}  —  {ts}  |  {sc}"
            labels.append(lbl)
        sel_label = st.selectbox("Select run", options=labels, index=0,
                                 help="Compare previous evaluation runs")
        sel_idx   = labels.index(sel_label)
        tel = list(reversed(history))[sel_idx]

    # ── Run metadata (fix #19) ────────────────────────────────────────────────
    ts      = tel.get("run_timestamp", "")
    scenario = tel.get("run_scenario", "")
    model    = tel.get("run_model", "")
    backend  = tel.get("run_backend", "")
    if ts:
        st.caption(
            f"🕒 {ts}  |  📋 {scenario or '?'}  |  "
            f"🤖 {model or '?'} ({backend})"
        )

    # Aborted warning
    if tel.get("run_aborted"):
        st.warning("⚠️  This run was aborted — metrics may be incomplete.")

    # ── Top summary metrics (fix #18: clearer labels + tooltips) ─────────────
    c1, c2, c3, c4, c5, c6 = st.columns(6)
    c1.metric("Latency",      f"{tel.get('total_latency', 0):.2f} s",
              help="Total wall-clock time from run start to completion")
    c2.metric("Total Tokens", tel.get("total_tokens", 0),
              help="Prompt tokens + completion tokens")
    c3.metric("Prompt",       tel.get("prompt_tokens", 0),
              help="Tokens in all messages sent to the model")
    c4.metric("Completion",   tel.get("completion_tokens", 0),
              help="Tokens generated by the model")
    c5.metric("Tok / sec",    f"{tel.get('tokens_per_second', 0.0):.1f}",
              help="Generation throughput (completion tokens / latency)")
    c6.metric("LLM Rounds",   tel.get("llm_rounds", 0),
              help="Number of LLM API calls made in this run")

    st.divider()

    # ── Export button (fix #27) ───────────────────────────────────────────────
    export_col, _ = st.columns([2, 5])
    with export_col:
        st.download_button(
            "⬇  Export Results (JSON)",
            data=json.dumps(tel, indent=2, default=str),
            file_name=f"spark_results_{tel.get('run_timestamp','run').replace(' ','_').replace(':','-')}.json",
            mime="application/json",
        )

    # ── Metrics evaluation ─────────────────────────────────────────────────────
    st.subheader("Metrics Evaluation")
    matrix: list = [m for m in st.session_state.get("metrics_matrix", []) if m.get("enabled")]

    if not matrix:
        st.info("No metrics enabled — configure them in **Configuration → Metrics Setup**.")
    else:
        results = [(m, evaluate_metric(m, tel)) for m in matrix]
        passed  = sum(1 for _, r in results if r is True)
        failed  = sum(1 for _, r in results if r is False)
        na      = sum(1 for _, r in results if r is None)

        s1, s2, s3, _ = st.columns([1, 1, 1, 4])
        s1.markdown(_badge(f"PASS {passed}", "#16a34a"), unsafe_allow_html=True)
        s2.markdown(_badge(f"FAIL {failed}", "#dc2626"), unsafe_allow_html=True)
        s3.markdown(_badge(f"N/A  {na}",     "#475569"), unsafe_allow_html=True)
        st.write("")

        # Group by category
        by_cat: dict[str, list] = {c: [] for c in CATEGORIES}
        for m, r in results:
            cat = METRIC_TYPES.get(m.get("type", ""), {}).get("category", "Validation")
            by_cat.setdefault(cat, []).append((m, r))

        for cat in CATEGORIES:
            items = by_cat.get(cat, [])
            if not items:
                continue
            colour = _CAT_COLOUR.get(cat, "#64748b")
            st.markdown(
                f'<div style="margin:12px 0 4px;font-weight:700;color:{colour}">'
                f'{cat.upper()}</div>',
                unsafe_allow_html=True,
            )
            hcols = st.columns([2, 4, 5, 2])
            for lbl, col in zip(["ID", "Name", "Criterion", "Result"], hcols):
                col.markdown(f"*{lbl}*")

            for m, result in items:
                rc = st.columns([2, 4, 5, 2])
                rc[0].code(m["id"])
                rc[1].write(m["name"])
                rc[2].markdown(
                    f'<div style="color:#e2e8f0; font-size:0.95rem; line-height:1.4;">{format_criterion(m)}</div>',
                    unsafe_allow_html=True,
                )
                if result is True:
                    rc[3].markdown(_badge("PASS ✓", "#16a34a"), unsafe_allow_html=True)
                elif result is False:
                    rc[3].markdown(_badge("FAIL ✗", "#dc2626"), unsafe_allow_html=True)
                else:
                    rc[3].markdown(_badge("N/A",   "#475569"), unsafe_allow_html=True)

    st.divider()

    # ── Tool calls detail ──────────────────────────────────────────────────────
    tool_calls: list = tel.get("tool_calls", [])
    if tool_calls:
        st.subheader(f"Tool Calls  ({len(tool_calls)})")
        for i, tc in enumerate(tool_calls):
            exit_code = tc.get("exit_code", "?")
            status    = "✓" if exit_code == 0 else "✗"
            label     = f"#{i+1}  {tc.get('tool','?')}  {status}  —  {tc.get('runtime',0):.3f} s"
            with st.expander(label):
                ca, cb = st.columns(2)
                with ca:
                    st.write("**Arguments**")
                    st.json(tc.get("args", {}))
                with cb:
                    st.write("**Result**")
                    result = tc.get("result", {})
                    st.json(result) if isinstance(result, dict) else st.code(str(result))
                st.caption(f"Exit code: {exit_code}")

    # ── Inefficiencies ─────────────────────────────────────────────────────────
    issues: list = tel.get("inefficiencies", [])
    if issues:
        st.subheader("Inefficiencies Detected")
        for iss in issues:
            st.warning(iss)

    st.divider()

    # ── Validation output ──────────────────────────────────────────────────────
    st.subheader("Validation Output")
    val_exit = tel.get("validation_exit_code")
    if val_exit is None:
        st.info("No validation command was run.")
    else:
        if tel.get("validation_passed"):
            st.success(f"PASS ✓  (exit code: {val_exit})")
        else:
            st.error(f"FAIL ✗  (exit code: {val_exit})")
        if tel.get("validation_stdout"):
            st.text_area("Stdout", value=tel["validation_stdout"], height=160)
        if tel.get("validation_stderr"):
            st.text_area("Stderr", value=tel["validation_stderr"], height=100)

    # ── Final LLM response ─────────────────────────────────────────────────────
    if tel.get("llm_response"):
        st.divider()
        st.subheader("Final LLM Response")
        st.write(tel["llm_response"])
